// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA_wTQaG-8ReN0EALriVv52KDvbU8M83Ek',
    appId: '1:691997851612:web:ce9c1428b99d7b23159919',
    messagingSenderId: '691997851612',
    projectId: 'project-mobile-programmi-25418',
    authDomain: 'project-mobile-programmi-25418.firebaseapp.com',
    storageBucket: 'project-mobile-programmi-25418.firebasestorage.app',
    measurementId: 'G-CHZHP0QCHD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAFaTwfMCfTx10qrc90k2Ftzr3SjCDJJlc',
    appId: '1:691997851612:android:477a4b166aa5ec7a159919',
    messagingSenderId: '691997851612',
    projectId: 'project-mobile-programmi-25418',
    storageBucket: 'project-mobile-programmi-25418.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDnFa66Ey1fBT3up3XOEehvjTWd8XsLD4Y',
    appId: '1:691997851612:ios:198629b166393bf0159919',
    messagingSenderId: '691997851612',
    projectId: 'project-mobile-programmi-25418',
    storageBucket: 'project-mobile-programmi-25418.firebasestorage.app',
    iosBundleId: 'com.example.projectMobileProgramming',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDnFa66Ey1fBT3up3XOEehvjTWd8XsLD4Y',
    appId: '1:691997851612:ios:198629b166393bf0159919',
    messagingSenderId: '691997851612',
    projectId: 'project-mobile-programmi-25418',
    storageBucket: 'project-mobile-programmi-25418.firebasestorage.app',
    iosBundleId: 'com.example.projectMobileProgramming',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA_wTQaG-8ReN0EALriVv52KDvbU8M83Ek',
    appId: '1:691997851612:web:0cd1561a3e229f8b159919',
    messagingSenderId: '691997851612',
    projectId: 'project-mobile-programmi-25418',
    authDomain: 'project-mobile-programmi-25418.firebaseapp.com',
    storageBucket: 'project-mobile-programmi-25418.firebasestorage.app',
    measurementId: 'G-VVFRQ3CGJK',
  );
}
